version: '3.4'

services:
  minimalapisimple:
    image: ${DOCKER_REGISTRY-}minimalapisimple
    build:
      context: .
      dockerfile: MinimalAPISimple/Dockerfile

  codefirstlearning.webapi:
    image: codefirstlearning.webapi
    build:
      context: .
      dockerfile: CodeFirstLearning.Webapi/Dockerfile
