name: .NET Core Deploy

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup .NET Core
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.x

    - name: Install dependencies
      run: dotnet restore ./MinimalAPIBySelf/MinimalAPIBySelf.csproj

    - name: Build
      run: dotnet build ./MinimalAPIBySelf/MinimalAPIBySelf.csproj --configuration Release --no-restore

    - name: Test
      run: dotnet test --no-restore --verbosity normal

    - name: Publish
      run: dotnet publish ./MinimalAPIBySelf/MinimalAPIBySelf.csproj --configuration Release --no-restore --output ./publish

    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./publish
